### PR TITLE
Handling failed api#90

### LINKED ISSUE #90: Handling failed API requests
If an api request fails, the page should still load

### PR DESCRIPTION
**Pull request by asmolentzov**
We want to make sure the page loads don't fail even if the weather API call does fail. 
- Adds logic to Dashboard page to check that we have weather data before trying to display it
- Adds `has_weather?` method to DashboardFacade
- Adds logic to Garden Index page to check that we have weather data before trying to display it
- Adds `has_weather?` method to GardenFacade. 
- All tests passing
Please let me know if there are other spots that you can think of that I should check! @bendelonlee 
 do you remember the page that you were on that prompted this card? 
This is something we should keep in mind if we add weather data/other API data to other pages. 
Closes #90

### CODE REVIEW

File: spec/features/users/user_can_still_see_pages_if_api_calls_fail_spec.rb [hunk 1]
```diff
@@ -0,0 +1,35 @@
+require 'rails_helper'
+
+describe 'As a logged in user of the site' do
+  describe 'on the dashboard' do
+    it 'can see the site even if API calls fail' do
```
Comment (le3ah) [inline spec/features/users/user_can_still_see_pages_if_api_calls_fail_spec.rb]: Love this.
